import {
  Flame,
  Zap,
  Brain,
  Target,
  Crown,
  Sparkles,
  Shield,
  Infinity,
} from "lucide-react";

export const STREAK_MILESTONES = [
  { days: 1, title: "First Step", icon: Sparkles },
  { days: 3, title: "Sparked", icon: Zap },
  { days: 5, title: "Focused", icon: Target },
  { days: 7, title: "Consistent", icon: Flame },
  { days: 10, title: "Unstoppable", icon: Flame },
  { days: 14, title: "Locked In", icon: Shield },
  { days: 21, title: "Habit Builder", icon: Brain },
  { days: 30, title: "Disciplined", icon: Target },
  { days: 45, title: "Relentless", icon: Flame },
  { days: 60, title: "Iron Will", icon: Shield },
  { days: 75, title: "Deep Focus", icon: Brain },
  { days: 90, title: "Beast Mode", icon: Flame },
  { days: 100, title: "Insane Sage", icon: Brain },
  { days: 120, title: "Monk Mode", icon: Brain },
  { days: 150, title: "Machine Mind", icon: Brain },
  { days: 180, title: "Unbreakable", icon: Shield },
  { days: 200, title: "Elite Operator", icon: Crown },
  { days: 250, title: "System Thinker", icon: Brain },
  { days: 300, title: "Timeless", icon: Infinity },
  { days: 365, title: "Legendary Architect", icon: Crown },
  { days: 730, title: "Myth", icon: Crown },
  { days: 1000, title: "Immortal", icon: Infinity },
];
